### ISSUE TITLE
Support long-plural-form and NewAcroCommand

### ISSUE THREAD

**Issue by UFOMelkor** [kprussing/pandoc-acro#8]
Currently, the filter supports a short and a long form and their plural suffixes.
For a language like English, I guess that is all you need. For other languages like German, you unfortunately need more forms, which cannot be accomplished by simply adding a suffix:

*Apfel* (nom. sg.) → *Äpfel* (nom. pl.)
*Bundesamt für Stahlenschutz* (nom. sg.) → *Bundesamtes für Strahlenschutz* (gen. sg.)

If I read and understand correctly, the *acro* package supports this with `long-plural-form`  and `NewAcroCommand` (for defining other cases). I think about a syntax like the following one:

```yaml
acronyms:
  Apple:
    short: AP
    long: Apfel
    long-plural-form: Äpfel
  BfS:
    short: BfS
    long: "Bundesamt für Strahlenschutz"
    long-genitive-form: "Bundesamtes für Strahlenschutz"
```

```markdown
Das englische Wort für [+Apple]{.plural} ist apples.
[+Apple]{.plural} werden von den Mitarbeitern des [+BfS]{.genitive} untersucht.
```

```txt
Das englische Wort für Äpfel (AP) ist apples.
APs werden von den Mitarbeitern des Bundesamtes für Strahlenschutz (BfS) untersucht.
```

Would you be fine if I give a try implementing this, or would you consider this out-of-scope for this filter?
